zlib-ng/minizip-ng

- ioapi.h
On these operating systems fopen, fseek, and ftello are 64-bit
filesize safe.
Signed-off-by: Thomas Klausner <wiz@NetBSD.org>
> Fix linking on NetBSD and DragonFly BSD.

- unzip.c
UNZ_EOF and UNZ_OK are both zero, so the caller of unzlocal_getByte has no way to know whether or not pi points to data or garbage. This change makes it point to zero in the EOF case. While it might be better to indicate an error immediately, that would be a more significant change. The library ought to be just as good at handling an erroneous zero byte as anything else; and this way dynamic analysis tools won't complain about use-of-uninitialized-value when reading a malformed file.
> Fix use-of-uninitialized-value warning.

- crypt.h
- unzip.c
Fixed bug in 64bit builds in pkware password archive extractions. Types around crc32 and pkeys reference tables have to be unsigned int not long.
> fix 64bit archives with password

- unzip.c
Fix the error "assignment from incompatible pointer type" when built on Linux platform.
> Assignment from incompatible pointer type

- zip.c
Signatures of certain parameters of crctables and pkeys were changed during the recent fix to support 64bit builds for archives with "PKWARE" password, but these changes were not reflected across all cases. The current changes would take care of any "assignment from incompatible pointer type" errors when built on other platforms.
> Fix parameter signatures

- CMakeLists.txt
Fixed ZLIB headers not being found if it's not in a default include location
> Fixed ZLIB headers not being found

- CMakeLists.txt
I'm experimenting with different versions of zlib (Intel/Kukunas, CloudFlare etc.) and I found it useful to be able to link minizip with a particular version out of those that I have available. I've modified the CMakeLists.txt to make this straightforward to do.
> Added ability to specify ZLIB_ROOT when using CMAKE

- CMakeLists.txt
Changed compiler flag "HAVE_AES" to be set by platform independent add_definitions
Added "-D_CRT_SECURE_NO_DEPRECATE" to WIN32 compiler and fPIC to gcc compiler
> Changed compiler flag "HAVE_AES" to be platform independent

- unzip.c
- unzip.h
I believe that the password verification bytes were intended to be checked.
I added a new error value, because I think the distinction would be useful in practice to handle the error.
> Check password verification bytes.

- Minizip.podspec
A podspec inside the repository itself will make it easier for wrappers (like [SSZipArchive](https://github.com/ZipArchive/ZipArchive), [mattconnolly/ZipArchive](https://github.com/mattconnolly/ZipArchive), [dexman/Minizip](https://github.com/dexman/Minizip), ...) to use Minizip as a dependency. It will also help [CocoaPods](https://cocoapods.org/) users to include Minizip in their projects, as they will simply have to write:
pod 'Minizip', :git => 'https://github.com/nmoinvaz/minizip.git'
or:
pod 'Minizip/Core', :git => 'https://github.com/nmoinvaz/minizip.git'
And if you decide to tag your releases on this repository and push your podspec to trunk, then people will be able to use semantic versioning:
pod 'nmoinvazMinizip', '~> 1.1'
> adding a podspec

- ioapi.c
I'm compiling minizip in my project by #including its source code inline (namely, `unzip.c` and `ioapi.c`) in MSVC 2015. I'll let the compiler speak for itself:
```
ioapi.c(201): error C2664: 'char *strncpy(char *,const char *,std::size_t)': cannot convert argument 2 from 'void *' to 'const char *'
ioapi.c(201): note: Conversion from 'void*' to pointer to non-'void' requires an explicit cast
```
There are two more in the same vein. This PR is a trivial fix for these errors.
> Fix error C2664 on MSVC 2015

- zip.c
Loop control variable 'write' never changed because 'written' was no longer assigned.
This causes the ZIP file to grow until disk is full.
> fix endless loop in zipFlushWriteBuffer() 

- minishared.c
This fix a missing underscore in the "dos_date" variable, preventing the compilation of the library on a unix-like machine.
> fix typo error in get_file_date()

- Makefile.am
Makefile.am got broken after https://github.com/nmoinvaz/minizip/commit/28ad5bf4fb7ceb1014e1d80c9b64ce52bb329329
This PR fixes it.
Without:
```
miniunz.o:miniunz.c:(.text+0x1e8): undefined reference to `dosdate_to_tm'
miniunz.o:miniunz.c:(.text+0x695): undefined reference to `makedir'
miniunz.o:miniunz.c:(.text+0x6eb): undefined reference to `change_file_date'
miniunz.o:miniunz.c:(.text+0x71a): undefined reference to `check_file_exists'
collect2.exe: error: ld returned 1 exit status
minizip.o:minizip.c:(.text.startup+0x270): undefined reference to `get_file_date'
minizip.o:minizip.c:(.text.startup+0x281): undefined reference to `is_large_file'
minizip.o:minizip.c:(.text.startup+0x4e9): undefined reference to `get_file_crc'
minizip.o:minizip.c:(.text.startup+0x572): undefined reference to …
```
> fix Makefile.am

- zip.c
This refactoring allows to deal with consistent pointee position to reduce manual offsetting. It also deals with the warning of `p` being unread (see #84).
> factoring zip64local_putValue_inmemory_andMoveP

- ioapi_buf.c
- zip.c
Xcode is giving warnings for unused values.
(maybe this pull request doesn't need to be merged as is, but it gives a hint to where we may have forgot to handle something)
> Value stored is never read

- Minizip.podspec
SSZipArchive is using minishared for its `tm_to_dosdate()`, so it's best to include minishared as a subspec.
> including minishared as an optional dependency

- zip.c
zipReadValueFromMemory is not declared in .h and is unused
> Unused function 'zipReadValueFromMemory'

- zip.c
pcrc_32_tab is `const z_crc_t *` (aka 'const unsigned long *')
get_crc_table is `const z_crc_t FAR *` (aka 'const unsigned long *')
And clang is unhappy with the previous cast:
>/minizip/zip.c:1235:32: Incompatible pointer types assigning to 'const z_crc_t *' (aka 'const unsigned long *') from 'const unsigned int *'
> avoid unnecessary cast

- unzip.c
MSVC didn't properly support C99 until MSVC 2015, so the extra ';' makes MSVC think that we've started adding statements. Hence, it fails because there are still some variable declarations after it.
> unzip.c: Removed an extra ';' that caused compile errors on MSVC 2010.

- minishared.c
The original code only initializes the first field which causes clang to spit out "missing field 'st_mode' initializer".
> Clear the stat struct properly to avoid compiler warning

- unzip.c
- zip.c
The warnings show up when some #ifdefs are not active.
> Move declarations to avoid unused warnings

- aes/brg_endian.h
- aes/fileenc.c
- aes/hmac.h
- aes/prng.c
- aes/pwd2key.c
This PR adds a support for PNaCl platform. Because PNaCl does not contain 
memory.h I changed it to string.h. Is this alright or should I rather use 
the preprocessor to determine which library we should include depending on a 
target platform?
> Add a support for PNaCl platform

- crypt.h
The issue is affecting users with [zlib 1.2.5](https://opensource.apple.com/source/zlib/zlib-61.20.1/) (available on Xcode 7.x), as it doesn't define z_crc_t yet.
This workaround is not needed anymore with [zlib 1.2.7](https://sourceforge.net/p/miranda/svn/14263/tree/trunk/miranda/plugins/zlib/) (1.2.8 is available on Xcode 8.3) as it defines z_crc_t in zconf.h.
> fix Unknown type name 'z_crc_t'

- zip.c
- zip.h
If we're using the File Time, then crc_for_crypting becomes __unused__
> __attribute__((__unused__)) for crc_for_crypting

- minishared.c
- minishared.h
In [minishared L137](https://github.com/nmoinvaz/minizip/blob/master/minishared.c#L137) we got this comment:
> (assumed to be between 1980 and 2107, typical output of old software that does 'year-1900' to get a double digit year)
Well, the 'year-1900' is not just for old software, it's because it's defined as a standard in ISO/IEC 9899: https://www.cs.helsinki.fi/group/boi2016/doc/cppreference/reference/en.cppreference.com/w/c/chrono/tm.html.
So when we're adding `+ 1980` on  [minishared L108](https://github.com/nmoinvaz/minizip/blob/master/minishared.c#L108), we're breaking a standard. We should instead be adding `+ 80` only (+ 1980 - 1900). Well, it's a bit late to fix it, so instead I'd like to introduce a helper to convert both a _standard_ `tm` and a _minizip_ `tm` to a `time_t` …
> fix miniunz files date for non-WIN32 and adding helper dosdate_to_time_t

- CMakeLists.txt
- aes/aes_ni.c
When using clang with -Werror and -Wunknown-pragmas flags, it will not compile successfully because GCC pragmas are not present in clang. This PR limits GCC pragmas to GCC compiler.
> Define GCC pragmas only for GCC compiler

- ioapi.c
- ioapi.h
- minishared.c
- minishared.h
On Windows, paths containing non ASCII characters were not supported. The reason is that fopen on Windows only supports ASCII characters in paths.
This change adds a define WINDOWS_SUPPORT_UNICODE_PATH which uses _wfopen instead of fopen64 on Windows. Tested on Windows 10.
> Add support for non-ASCII characters in paths on Windows

- unzip.c
> ignoring size_filename to avoid failing unzipping

- ioapi.c
- ioapi.h
- ioapi_buf.c
- ioapi_mem.c
- zip.h
Fix all the unused parameter warnings generated by -Wunused-parameter on macOS with Xcode 9.
> Fix unused parameter warnings generated by -Wunused-parameter

- Minizip.podspec
I've removed the subspec for minishared, as apparently it's tools are now included in mz_strm.h.
> Podspec for 1.3.0

- zip.c
- zip.h
This pull request is for adding the possibility of optional AES on Minizip1 with minimal impact.
(I do appreciate the work on Minizip2, but it's a long way before we get the time to migrate)
> allowing AES to be optional at runtime

- src/mz_os_win32.c
When compiling under mingw-w64, "errno.h" must be included to define EEXIST
> Include "errno.h" to define EEXIST

- src/mz_compat.h
with original zlib/contrib/minizip API
> mz_compat.h: add type zipcharpc for compatibility

- src/mz_compat.c
mz_compat.c fails to compile because "mz_error.h" no longer exists.  It should include "mz.h" instead.
> "mz_error.h" no longer exists

- src/minizip.c
- src/mz_compat.c
- test/test.c
While trying to update my ROM Properties Page plugin to use MiniZip 2.2.3, I encountered several issues in the mz_compat layer that caused crashes and other random problems. One of these problems were already fixed here before I had the chance to send the PR (build without encryption).
This PR has:
* Correctly dereference `pzlib_filefunc_def`. This is only an issue if the MiniZip 1.x vtable is set manually, which I was doing in order to handle Unicode filenames on Windows.
* unzClose(): Close the file handle. A similar fix for zipClose2_64() was applied in commit 053d00c451e102464e680069cd1ed6cae4171dc6.
* unzGetCurrentFileInfo64(): Make sure `filename` and `comment` are NULL-terminated.
* unzOpen2_64(): Go to the first file immediately.
* Some printf() fixes found with cppcheck-1.81.
> Fixes for the mz_compat layer.

- src/mz_compat.c
The previous bugfixes fixed the functions that took a zlib_filefunc_def* parameter, but they inadvertently broke the functions that didn't. The fix is to store the filefunc pointer locally, then pass a pointer to the pointer.
> mz_compat.c: Fix zipOpen(), zipOpen64(), and unzOpen64().

- unzip.c
This change adds a quick check for the password upon file open, for Traditional PKZIP encryption.
It will avoid that the applications continue to read incorrect data when wrong password is entered.
The verification logic is noted in the documents published by http://www.info-zip.org/doc/.
We would like to have this fix in the 1.2 branch because Zip Archiver extension for ChromiumOS depends on it.
https://bugs.chromium.org/p/chromium/issues/detail?id=782197
> Verify decrypted header to detect wrong password for Traditional PKZIP.

- CMakeLists.txt
- src/mz_strm_posix.c
This PR fixes a few functions in `mz_strm_posix.c` to check for the right failure conditions in the POSIX stdio API.
> mz_strm_posix: Fix return value checking for POSIX stdio functions

- CMakeLists.txt
This allows a parent project to use minizip via:
add_subdirectory(path/to/minizip)
without the compiler flags of the parent project being affected.
> CMakeLists.txt: Use add_compile_options() instead of modifying CMAKE_C_FLAGS

- CMakeLists.txt
These fixes should make it easier to install minizip as a system library on Linux. I'm not sure what effect they will have on Windows or MacOS, but I would hope that GNUInstallDirs does something sensible there.
> Cmake fixes

- src/mz_zip.c
Previously, the conditions for writing 32-bit vs 64-bit data descriptor
fields were swapped. If the size was smaller than UINT32_MAX, a 64-bit
integer would be written, and if the size was larger, then a truncated
32-bit integer would be written. This prevented programs that don't have
support for the central directory (like busybox) from reading files
created by minizip.
> mz_zip.c: Fix incorrect size of data descriptor fields

- CMakeLists.txt
Android APIs < 24 don't have support for the POSIX LFS API and will
fail at link time if the macros are defined.
See: https://github.com/android-ndk/ndk/issues/442
> cmake: Don't define LFS macros on Android API < 24

- CMakeLists.txt
CMake will figure out the right compiler arguments to use for enabling
PIC on the target platform.
> cmake: Use POSITION_INDEPENDENT_CODE property instead of setting -fPIC

- CMakeLists.txt
Previously, these optimizations would get enabled when building for
non-x86 architectures using Clang, which would cause a warning to be
output.
> cmake: Enable x86 optimizations only if supported

- src/mz_strm_win32.c
mz_stream_win32_open opens the stream in exclusively mode if mode & MZ_OPEN_MODE_READWRITE) == MZ_OPEN_MODE_READ.
Likely it is a bug, and it is not clear what is expected behavior.
Just keep FILE_SHARE_READ to allow shared read access to the stream.
> keep FILE_SHARE_READ if MZ_OPEN_MODE_READ

- src/mz_zip.c
Value for `disk_number` would never be read from the ZIP64 extension field since the check to see if it has the value 0xFFFF never succeeds.
> Fix: Field disk_number is 16bit, will never contain UINT32_MAX.

- src/mz_compat.c
- src/mz_zip.c
Currently the implementation for NTFS file times extra field writes only the timestamps different from zero:
https://github.com/nmoinvaz/minizip/blob/7a3820c53912d3c004c493b0ad1811864ccfe8c1/src/mz_zip.c#L883-L889
From the APPNOTE.TXT I understand that the extra field should contain all the three timestamps (or not be used at all). Since I'm no expert, I peeked at a few ZIP libraries/utilities source code. Multiplatform utilities (like InfoZIP) usually skip the field altogether or do not parse its contents. So I focused on libraries targeting the Windows system and (IMHO) are the most relevant. To cite some examples, SharpZipLib will ignore the extra field if tag data length is different from 24 bytes. DotNetZip will fail with an exception if the extra field total length is different from …
> Fix ntfs extra field

- src/mz_strm_crypt.c
Reapplies https://github.com/nmoinvaz/minizip/pull/136 to minizip 2.x from @Coeur into minizip 2.x to support Xcode 7.
> Fix Unknown type name 'z_crc_t' in minizip 2.x

- CMakeLists.txt
- minizip.pc.cmakein
- cmake automatically adds `lib` to the project name for shared mingw builds and produces `liblibminizip.dll.a`
- `-lz` needs to come after `-lminizip` for static linking
> Minor fixes for mingw cross-compilation

- src/mz_strm_lzma.c
- src/mz_zip.c
Fixes decompressing LZMA streams without EOS marker, which is indicated by bit 1 turned off in general purpose bit flag (APPNOTE.TXT section 4.4.4).
I have absolutely no experience using LZMA library so it would be good if someone could check this. The only documentation I found was the Javadoc for the XZ library, which states that when EOS is missing, the library user must know both the compressed size to limit the compressed stream reads, and the uncompressed size to limit the output buffer writes, otherwise the decompressor might produce more output than the original (e.g., when decompressing nices/DirectX-setup/DSETUP.dll from the test file, an extra 0x00 byte is produced).
> Fixes #233

- mz_compat.c
- mz_compat.h
- mz_zip.c
- mz_zip.h
* Fix NULL pointer dereference when calling `zipOpen*()` or `unzOpen2*()` with NULL filefunc table.
* Rename `dos_date` to `dosDate` in zip/unzip structures to be compatible with original minizip.
* Add tm struct timestamps to zip/unzip structures and populate them with the `dosDate` value for unzip and use the value passed into it on zip, if `dosDate` is zero (mimicing original minizip behaviour.)
* Change `zipWriteInFileInZip()` return value to be a status code (`ZIP_OK` or `ZIP_ERRNO`) instead of the number of bytes written. This way it's minizip compatible.
* Add `zipCloseFileInZipRaw64()` compatibility wrapper.
* Add these compatibility functions:
`unzGetOffset()`
`unzGetOffset64()`
`unzSetOffset()`
`unzSetOffset64()`
* Add stub for compatibility: `unzGetLocalExtrafield()`
It will …
> improve compatibility with original minizip

- mz_zip.c
in function `mz_zip_entry_write_open()`
Fixes https://github.com/nmoinvaz/minizip/issues/255
> fix to set MZ_ZIP_FLAG_LZMA_EOS_MARKER flag in raw mode

- mz_zip.c
- mz_zip.h
```
mz_compat.c:390:62: warning: passing 'uint32_t *' (aka 'unsigned int *') to parameter of type
'int32_t *' (aka 'int *') converts between pointers to integer types with different sign [-Wpointer-sign]
err = mz_zip_get_disk_number_with_cd(compat->handle, &pglobal_info->number_disk_with_CD);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mz_zip.h:112:70: note: passing argument to parameter 'disk_number_with_cd' here
extern int32_t mz_zip_get_disk_number_with_cd(void *handle, int32_t *disk_number_with_cd);
^
```
> fix cast warning (seen with LLVM/Clang)

- mz_compat.c
- mz_os_posix.c
- mz_strm.c
- mz_strm_aes.c
- mz_strm_buf.c
- mz_strm_bzip.c
- mz_strm_crypt.c
- mz_strm_lzma.c
- mz_strm_mem.c
- mz_strm_posix.c
- mz_strm_split.c
- mz_strm_win32.c
- mz_strm_zlib.c
- unused parameters
- trivial const stripping cases
- missing NULL initializers from vtbls
- missing static scope for vtbls
Missing newlines at EOF addressed in a separate PR.
It's be nice to replace `ZIP_UNUSED var` and `(void)var`
with a global and non-gcc-specific solution, such as:
```c
#define MZ_UNUSED(symbol)  (void)symbol
```
> silence various warnings

- mz_compat.h
(Only Windows needs this __declspec)
> Fix build on macOS

- mz_compat.h
This is defined in zutil.h in zlib, which is a private
header, so it doesn't get defined when #including zlib.h.
Instead if does get defined by minizip1 in zip.h, so
let's keep doing the same here as well.
Ref: https://github.com/madler/zlib/blob/v1.2.11/contrib/minizip/zip.h#L79-L85
Regression since: https://github.com/nmoinvaz/minizip/commit/ea99a46b6d36a11bc3e3eb3a806482d68ab4a991
> restore DEF_MEM_LEVEL constant in mz_compat.h

- mz_compat.c
This syncs this behaviour with original minizip (as of 1.2.11)
Ref: https://github.com/nmoinvaz/minizip/issues/289#issuecomment-408515522
> fix zipOpenNewFileInZip*() to allow passing level in raw mode

- CMakeLists.txt
Checks if BZip2 installation is present and link against the system one if so.
Previous discussion: #296
> use system Bzip2 library if available

- mz_zip_rw.c
writer->mem_stream is leaked when mz_zip_writer_open_file_in_memory is used.
I think this is because mem_stream is not closed at mz_zip_writer_close.
> fix mem_stream leak.

- CMakeLists.txt
**Error information:**
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
CMake Error at CMakeLists.txt:125 (if):
if given arguments:
"LESS" "24"
Unknown arguments specified
-- Configuring incomplete, errors occurred!
**The cmake docments about of if:**
if(<variable|string> LESS_EQUAL <variable|string>)
True if the given string or variable’s value is a valid number and less than or equal to that on the right.
> Fix: if(<variable|string> LESS_EQUAL <variable|string>)

- mz_strm.c
- mz_strm_mem.c
While I was fuzzing a program of mine, I encountered an infinite loop. The input file was obviously malformed, and minizip was trying to copy N bytes from a stream with M bytes (N > M). In that case, the limit is reached and `mz_stream_mem_read` does not return any bytes. That causes an infinite loop in `mz_stream_copy`.
> Fix infinite loop if a read operation does not return any bytes

- CMakeLists.txt
- lib/liblzma/check/check.c
- minizip.c
- mz_compat.c
- mz_os.c
- mz_os.h
- mz_os_posix.c
- mz_strm_buf.c
- mz_strm_crc32.c
- mz_strm_split.c
- mz_strm_zlib.c
- mz_zip.c
- mz_zip_rw.c
- mz_zip_rw.h
* enable `-W -Wall` for gcc and clang
* fix `strncpy()` calls that may potentially leave the target buffer without
a terminating zero byte (in `mz_zip_rw.c`)
* fix warnings
* remove `const` from `mz_path_remove_filename()` parameter,
the function is writing the passed buffer
* fix pedantic warnings (in `mz_strm_buf.c`):
`warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]`
* fix spaces at EOL
* fix a redefinition warning for `HAVE_ARC4RANDOM_BUF` on macOS
> enable warnings for gcc/clang, misc minor fixes

- mz_zip_rw.c
The time comparison was wrong and thus progress_cb was called every
second second instead of every second as intended.
> Make sure progress_cb is called every second

- mz_os_posix.c
- mz_os_posix.h
- mz_os_win32.c
- mz_os_win32.h
- mz_zip_rw.c
- mz_zip_rw.h
With mz_zip_reader_set_progress_interval the user can specify how
often in milliseconds the progress callback should be called. This
makes it possible to make a smoother progress bar when using
minizip from a GUI application.
> Add mz_zip_[reader,writer]_set_progress_interval

- mz_zip_rw.c
- mz_zip_rw.h
The pointer is passed to a function which expects a non-const pointer, and that function actually fills the buffer with data read from ZIP entries.
> mz_zip_reader_entry_read: remove const from buf parameter

- CMakeLists.txt
Only msvc toolchain need minizip.lib . then mingw toolchain need libminizip.lib
> Modify  target proerty to minizip in only msvc

- mz_compat.c
- remove unused variables
- fix signedness disagreement:
```
mz_compat.c:961:27: warning: comparison of integers of different signs: 'int64_t' (aka 'long long') and 'uint64_t'
(aka 'unsigned long long') [-Wsign-compare]
if (compat->total_out == file_info->uncompressed_size)
~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This one remains:
```
mz_zip.c:986:57: warning: cast from 'const unsigned char *' to 'void *' drops const qualifier [-Wcast-qual]
mz_stream_mem_set_buffer(extrafield_ms, (void *)file_info->extrafield, file_info->extrafield_size);
^
```
> mz_compat.c: fix warnings

- mz_zip.c
This will prevent the zip context to free multiple times the comment value, if for some reason the close function is called several times.
> Avoid double free on comment

- unzip.c
zlib uses uInt (`unsigned int`) for avail_in and avail_out.
This type can be limited to 64k and still conform to ANSI C,
but on most platformsit's bigger.
Remove some unnecessarily-narrow casting and only enforce
the actual limit (UINT_MAX), which might be 64k or might be larger.
This is per the recent discussion at the end of #91 and is essentially a version of the fix for #201 (3064a0e5519ddd360d104b45964c734b2b5ec5cb and 930f9188a5fb39947812d21306c6ae587fbe7c66) for the 1.2 branch
> Allow reading > 64k at a time on platforms where zlib supports this

- .travis.yml
- lib/brg/hmac.c
- lib/liblzma/common/memcmplen.h
- fix a typo in a cast
- fix wrongly falling into an #if branch meant for MSVC
when built with clang + mingw-w64
- remove a duplicate option from .travis.yml
- whitespace fixes
> misc fixes

- mz_zip.c
If the sum of day/month/year elements exceeds 32767, ubsan will tag it as undefined behaviour since the tm struct elements are int which is only defined to be at least 16-bits and signed. Casting these elements to uint32_t guarantees the calculations will be defined.
> Cast day/month/year elements to uint32_t

- mz_crypt.c
- mz_crypt_win32.c
Fixes a couple of bugs on windows caught by AppVerifier
- in function `mz_crypt_pbkdf2(..)`, `CryptDeleteHash` was being called after the associated Crypt context was released
- hmac1 and hmac2 are created using `mz_crypt_hmac_init`, so they each get their own context (provider) from the `CryptAcquireContext(..)` function
- hmac3 is created using `mz_crypt_hmac_copy`, which creates a duplicate of hmac2's hash, sharing the same context
- During destruction, hmac1 and hmac2 were being deleted first, followed by hmac3. This meant that the crypt contexts were released first by `CryptReleaseContext`. The subsequent call to `CryptDestroyHash(..)` on hmac3's hash would lead to UB as the associated context has already been released by that point
- Fix: call `mz_crypt_hmac_delete(..)` on hmac3 …
> Fix use after context release

- mz_zip.c
When a password-protected archive doesn't use password for its content, it shouldn't error out.
Here is a sample file
[EmptyWithParentDirectory.zip](https://github.com/nmoinvaz/minizip/files/3134399/EmptyWithParentDirectory.zip)
(taken from unit test `testZippingAndUnzippingEmptyDirectoryWithPassword` in temporary branch https://github.com/ZipArchive/ZipArchive/tree/minizip286)
> Unzipping password protected files with no password

- mz_zip.c
The creation of empty archives (with 0 entries) got broken by https://github.com/nmoinvaz/minizip/commit/64faa259d5acc39b842b2eab4eb5b1568acf3ce0.
We do want a Central Directory, otherwise the file created would be 0 bytes and not a valid zip file.
> Fix support for creating empty archives

- mz_crypt_apple.c
[CMSDecoder](https://developer.apple.com/documentation/security/cmsdecoder) is only on macOS, not on iOS or tvOS.
> Allowing compilation on iOS/tvOS when MZ_ZIP_NO_SIGNING is defined

- lib/brg/aescrypt.c
- lib/brg/aesopt.h
- lib/brg/brg_types.h
- lib/brg/sha2.c
- lib/bzip2/bzlib.c
- lib/bzip2/bzlib.h
- lib/liblzma/api/lzma/base.h
- lib/liblzma/api/lzma/lzma12.h
- lib/liblzma/api/lzma/vli.h
- lib/liblzma/lz/lz_decoder.c
Fixing third-parties typos.
###for BRG
I'll try to PR the same corrections later at:
https://github.com/BrianGladman/aes
https://github.com/BrianGladman/sha
###bzip2
Original (http://bzip2.org) doesn't exist anymore. So I can't PR upstream, unless you tell me where is the current reference repository. Is it one of those?
- https://sourceforge.net/projects/mingw/files/MSYS/Base/bzip2/bzip2-1.0.6-1/
- https://sourceforge.net/projects/mingw/files/MinGW/Extension/bzip2/bzip2-1.0.6-4/
- https://github.com/kjn/lbzip2
###lzma
I'm not sure if the original is here or not:
https://sourceforge.net/projects/sevenzip/files/LZMA%20SDK/
But if it is, then it's download-only and I can't make PR. Maybe I could try opening a ticket.
> Third-parties typos

- .travis.yml
- Minizip.podspec
This updates the podspec for the new files (mz.h, mz_os_posix.c, etc.).
This adds a job in travis to validate that the default_subspecs are installable.
> Podspec update

- mz_strm_zlib.c
There's a missing `break;` in the switch/case of `mz_stream_zlib_get_prop_int64()` when prop is `MZ_STREAM_PROP_COMPRESS_WINDOW`, resulting in a `MZ_EXIST_ERROR` return instead of `MZ_OK`.
> Fix return of mz_stream_zlib_get_prop_int64() for PROP_COMPRESS_WINDOW

- CMakeLists.txt
When using the Ninja generator, CMake relies on the BUILD_BYPRODUCTS argument of ExternalProject_Add to determine how to build libz.a. 
Previously this was wrongly set to the empty variable `ZLIB_STATIC_LIBRARIES` instead of `ZLIB_LIBRARIES`.
> Fix BUILD_BYPRODUCTS argument for zlib

- mz_strm_zlib.c
Fixes #414 in zlib by continuing to loop until no work is done, an error is produced, or the output buffer is full.  (Previously, it would also break if no input was provided, but zlib can continue to output as needed if the output buffer is too small to take everything.)
> Fix issue with truncated ZLIB output.

- mz_os_win32.c
Exprienced in a mingw-w64 + clang-9 cross-build environment:
```
mz_os_win32.c:560:22: error: use of undeclared identifier 'SYMBOLIC_LINK_FLAG_DIRECTORY'
flags |= SYMBOLIC_LINK_FLAG_DIRECTORY;
^
mz_os_win32.c:632:91: warning: incompatible pointer types passing 'int32_t *' (aka 'int *') to parameter of type 'LPDWORD' (aka 'unsigned long *')
[-Wincompatible-pointer-types]
if (DeviceIoControl(handle, FSCTL_GET_REPARSE_POINT, NULL, 0, buffer, sizeof(buffer), &length, NULL) == TRUE)
^~~~~~~
/usr/local/opt/mingw-w64/toolchain-x86_64/x86_64-w64-mingw32/include/ioapiset.h:22:175: note: passing argument to parameter 'lpBytesReturned' here
WINBASEAPI WINBOOL WINAPI DeviceIoControl (HANDLE hDevice, DWORD dwIoControlCode, LPVOID lpInBuffer, DWORD nInBufferSize, LPVOID lpOutBuffer, DWORD …
```
> fix Windows-specific compiler error and warnings

- README.md
This recommendation is to avoid scenarios like #429, especially on macOS.
> Specifying the minimum recommended version of cmake

- mz_os_win32.c
The kernel32.dll pathname code had two issues:
1. Using sizeof() for wchar_t[]. sizeof() returns the number of bytes, but the wcs*() functions need number of characters, so we end up telling wcsncat() that the buffer is twice as big as it actually is.
2. wcsncat()'s size parameter is supposed to be the *remaining* size in the buffer, not the total size. wcscat_s() should be used instead, since it takes the total size of the buffer.
None of this is actually needed, since kernel32.dll is used by all Windows programs, so it's always loaded in memory.
> mz_os_win32.c: kernel32.dll is always loaded, so use GetModuleHandleW().

- mz_crypt.c
- mz_strm_zlib.c
when build zlib-ng with zlib-compat and ZLIB_COMPAT-ON,
error like this:
/home/minizip/minizip-2.9.1/mz_crypt.c:19:14: fatal error:
-ng.h: No
such file or directory
include "zlib-ng.h"
/home/minizip/minizip-2.9.1/mz_strm_zlib.c:19:12: fatal error:
zlib-ng.h: No such file or directory
include "zlib-ng.h"
Signed-off-by: Chunmei Xu <xuchunmei@linux.alibaba.com>
> fix build error with zlib-ng compat

- .github/workflows/fuzz.yml
OSS-Fuzz was wondering if minizip would dogfood CIFuzz, a new feature being rolled out in OSS-Fuzz. It allows for pull requests to be fuzzed in CI using fuzz targets enabled in OSS-Fuzz. It will be active in dry_run mode meaning that it will never fail. Documentation for this feature can be found [here](https://google.github.io/oss-fuzz/getting-started/continuous-integration/). Let us know if you have any questions!
> CIFuzz Dog Food

- CMakeLists.txt
Hi! 
This adds the build directory to the `target_include_directories` using the BUILD_INTERFACE generator. That way, minizip does not have to be installed when used as a subproject.
> CMakeLists: allow to use minizip as a subproject with add_subdirectory

- mz_os_posix.c
```
mz_os_posix.c:99:13: warning: passing 'uint8_t *' (aka 'unsigned char *') to parameter of type 'char *' converts between pointers to
integer types with different sign [-Wpointer-sign]
strncpy(string_copy, string, string_length);
^~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_string.h:128:28: note: expanded from macro 'strncpy'
__builtin___strncpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
^~~~
```
> mz_os_utf8_string_create() fix warning with a cast

- mz.h
As [discussed](https://github.com/ZipArchive/ZipArchive/issues/572#issuecomment-634772990) this lets the compiler check for header availability.
I left the checks for `HAVE_STDINT_H` and `HAVE_INTTYPES_H` in CMakeLists, as they still seem to be used in liblzma.
> Use __has_include instead of preprocessor defines.

- mz.h
The defines using the "ll" prefix should be used on 64-bit, not 32-bit.
This is only used if `HAVE_INTTYPES_H` is not defined, which is probably why it hasn’t been caught before.
> Fix incorrect built-in PRIx64 defines

- CMakeLists.txt
Use pkg-config to find openssl libraries otherwise minizip will fail to
retrieve openssl static dependencies such as -latomic and build of
test_cmd will fail on:
```
[100%] Linking C executable test_cmd
/home/test/autobuild/run/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/8.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: /home/test/autobuild/run/instance-3/output-1/host/sparc-buildroot-linux-uclibc/sysroot/usr/lib/libcrypto.a(bio_lib.o): in function `BIO_free':
bio_lib.c:(.text+0x510): undefined reference to `__atomic_fetch_sub_4'
```
Fixes:
- http://autobuild.buildroot.org/results/b54b625751a45d3b449fffcdfaa06fb9209b4652
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> CMakeLists.txt: use pkg-config to find openssl

- mz.h
- mz_zip.c
See: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
```txt
0 - The file is stored (no compression)
1 - The file is Shrunk
2 - The file is Reduced with compression factor 1
3 - The file is Reduced with compression factor 2
4 - The file is Reduced with compression factor 3
5 - The file is Reduced with compression factor 4
6 - The file is Imploded
7 - Reserved for Tokenizing compression algorithm
8 - The file is Deflated
9 - Enhanced Deflating using Deflate64(tm)
10 - PKWARE Data Compression Library Imploding (old IBM TERSE)
11 - Reserved by PKWARE
12 - File is compressed using BZIP2 algorithm
13 - Reserved by PKWARE
14 - LZMA
15 - Reserved by PKWARE
16 - IBM z/OS CMPSC Compression
17 - Reserved by PKWARE
18 - File is compressed using IBM TERSE (new)
19 - IBM LZ77 z Architecture …
```
> Update zstd magic number to comply with the latest zip specification

- .github/workflows/main.yml
Hi.
I noticed the that the windows package is missing in the lastest release [2.10.0](https://github.com/nmoinvaz/minizip/releases/tag/2.10.0) due to [this commit](https://github.com/nmoinvaz/minizip/commit/4e0bc12f94ea8487041c2ac79c524e4d242ec46b), so I re-added the deploy settings to Windows MSVC job
> Restore Windows deploy in workflows

- mz.h
gcc 4.8 does not support __has_include directive as a result the build
will fail on:
```
/home/naourr/work/instance-1/output-1/build/minizip-2.10.0/mz.h:162:44: error: missing binary operator before token "("
(defined(__has_include) && __has_include(<stdint.h>))
^
```
Fix it by appling:
https://gcc.gnu.org/onlinedocs/gcc-10.1.0/cpp/_005f_005fhas_005finclude.html
Fix #510
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> mz.h: fix build with gcc 4.8

- CMakeLists.txt
Create CMake package config + version file.
I tried not to departure too much from the code in the master branch.
The installation directory is different in the master branch, because the 1.2 branch already installs a `minizip-exports.cmake` file into a different directory.
> Create cmake package config in 1.2 branch

- mz_strm_os_posix.c
the correct usage minizip on Android should be as below.
when api level >= 24, use default config.
when api level < 24, set MZ_FILE32_API=ON to avoid using fseeko/ftello
ref #488
> Remove usage of lseek64 on Android.

- mz_compat.c
- mz_compat.h
- zipOpenNewFileInZip*(): method/compression_method is 'int' in minizip1
- zipCloseFileInZipRaw64(): uncompressed_size is 'ZPOS64_T', which is 'uint64_t'
- unzTell64(): return value is 'ZPOS64_T', which is 'uint64_t'
- unztell(): return value should be 32-bit
- add unztell64() (full lowercase), which is the same as unzTell64()
- add unzeof(), which is the same as unzEndOfFile()
NOTE: It'd be probably useful to update mz_zip_entry_close_raw() uncompressed_size type to unsigned.
> mz_compat: sync parameter types with minizip1, add 2 compatibility wrappers

- mz_zip_rw.c
In contrast to other mz_*_create() functions, mz_zip_reader_create and mz_zip_writer_create crash on a null argument. This fixes it.
> mz_zip_rw.c - fix potential null dereference in create functions

- mz_crypt_openssl.c
- mz_os.h
- mz_os_posix.c
midipix is a POSIX layer like cygwin for windows.
LibreSSL 2.7.0 and above has added the HMAC_CTX_{new,free,reset} functions.
> Support building for midipix and LibreSSL 2.7.0+

- CMakeLists.txt
- README.md
This adds an additional CMake option, that allows the user to disable iconv. We support non-Windows systems that have iconv, but we don't want to use it on that system, so adding this switch has been proven to be quite useful.
> CMakeLists.txt - Introduce MZ_ICONV

- mz_compat.c
Allow getting filename/extrafield/comment separately without specifying an unz_file_info structure to improve compatibility with minizip1.
Fixes issue #535.
> mz_compat: support unzGetCurrentFileInfo without pfile_info

- doc/README.md
There is a small typo in doc/README.md.
Should read `versions` rather than `verisons`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, verisons -> versions

- CMakeLists.txt
FetchContent allows users to define the path to a prepopulated source folder by setting `FETCHCONTENT_SOURCE_DIR_<ID>`.
This will skip downloading and populating the repo, but also overrides `SOURCE_DIR`.
Hence you shouldn't make assumptions on where the fetched sources will be.
> Fix inclusion of fetched bzip2 sources

- mz.h
- test/test.c
_WIN32 is commonly used and more supported than _WINDOWS pre definition.
The official predefines supported by Visual Studio are listed here: https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160
This PR is related #475, but won't fix that, because only when MZ_COMPAT is enabled that minizip-ng provides external symbols.
/cc @impark @SpaceIm
> Replace _WINDOWS by _WIN32

- CMakeLists.txt
This simple change made cmake install relative and this is required to make minizip-ng properly in vcpkg
this change results in changing minizip-ng.cmake
old:
```cmake
set(_IMPORT_PREFIX "/usr/local/")
```
new
```cmake
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
set(_IMPORT_PREFIX "")
endif()
```
> made cmake _IMPORT_PREFIX relative

- minishared.c
- zip.c
The first commit is self-explanatory: After fixing the year offset, we should verify the fixed object, not the original.
The second commit fixes a bug intruduced in [28ad5bf4fb7ceb1014e1d80c9b64ce52bb329329 ](https://github.com/think-cell/minizip-ng/commit/28ad5bf4fb7ceb1014e1d80c9b64ce52bb329329):
- back then, the `tmz_date` member of `zip_fileinfo` was removed (see  [`zip.h`](https://github.com/think-cell/minizip-ng/commit/28ad5bf4fb7ceb1014e1d80c9b64ce52bb329329#diff-da89eb1436a2da88656a727b287191971d66bac1fbf4f975f2d9e9aec5505dd2))
- but before, setting `dos_date` to `0` was a flag to use this member. The code path checking that was removed (see [`zip.c`](https://github.com/think-cell/minizip-ng/commit/28ad5bf4fb7ceb1014e1d80c9b64ce52bb329329#diff-d334166fc820d9710f69cd137d12c36001349b …
> fixing dos_date bugs

- mz_crypt_openssl.c
BoringSSL does not provide cms.h but this is an optional dependency for
minizip, conditional on defined(MZ_ZIP_SIGNING).
For the functions called by mz_crypt_init:
- The OpenSSL_add_all_algorithms function is declared in evp.h.
OpenSSL's hmac.h includes evp.h but BoringSSL's hmac.h does not.
- The ERR_* functions are declared in err.h in both.
- The ENGINE_* functions are declared in engine.h in OpenSSL but are in
crypto.h for BoringSSL.
> Make mz_crypt_openssl.c work with BoringSSL

- mz.h
With this change minizip-ng can be built successfully on an alternative compiler for embedded systems. As the compiler doesn't define \_\_INT8_TYPE__ etc. it was redefining int8_t etc.
> Replace use of GNU C definitions with standard definitions in mz.h

- minizip.pc.cmakein
`INSTALL_LIB_DIR` is set to `CMAKE_INSTALL_LIB_DIR`, and while `CMAKE_INSTALL_PREFIX`
is prepended during install [1], this is not the case for the pkg-config
file. Thus, use the full absolute path `CMAKE_INSTALL_FULL_LIBDIR` for generating
the pkg-config file lib directory variables.
I originally saw this issue while building a package `vfrnav` which indirectly depended on minizip, where `libtool` complained that `lib64` did not exist because `-Llib64` was being passed to the linker, which was coming from minizip's pkg-config file [2].
[1] https://gitlab.kitware.com/cmake/cmake/-/issues/20250
[2] https://src.fedoraproject.org/rpms/libpqxx/pull-request/7
> pc: use absolute lib directory

- minizip.pc.cmakein
With commit 503bfd5c179b the CMake `_IMPORT_PREFIX` has been changed to relative paths.  This breaks the paths reflected by the auto-generated pkgconfig file, as pkgconfig expects those paths to be absolute.
***
Closes #584.
> minizip.pc: Ensure variables point to an absolute path.

- CMakeLists.txt
In Linux (and BSD) the `SOVERSION` only consists of the major version number. The correct symbolic links have to be
```
libminizip.so -> libminizip.so.3
libminizip.so.3 -> libminizip.so.3.0.2
libminizip.so.3.0.2
```
and the SONAME of libminizip.so.3.0.2 is `libminizip.so.3`. By this change the symbolic links are created correctly.
On other platforms, such as Windows and macOS, the `SOVERSION` may well consist of `<major-minor>`. That's why I added the if-else statement.
See also: https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html
> Fix SOVERSION in Linux

- .github/workflows/main.yml
- CMakeLists.txt
Using the PSPDEV homebrew SDK it is possible to build minizip for the Playstation Portable, but it does not support position independent code.
> Make minizip buildable for PSP

- .github/workflows/main.yml
- mz_os.c
The path may be overrun by two bytes. One because mz_path_append_slash
may append to path without updating path_len, and another one because
strncat always appends a NUL byte after writing N bytes.
Rescan the path length and subtract one from the strncat length parameter
to make sure we stay within max_path.
> Fix buffer overrun in mz_path_combine

- .github/workflows/main.yml
- .gitignore
When minizip-ng is used as a git submodule in a project where MZ_COMPAT is enabled, VS Code's Git integration will highlight zip.h and unzip.h as untracked files, which is annoying.
> Add .gitignore, ignoring MZ_COMPAT generated files

- mz_os_posix.c
- test/test.c
mz_os_get_file_date (on a file, or on a directory without a trailing slash) was broken by commit fe36527157ff96226f5309a99c806475ee0b75d2 , which always truncates the filename before passing it to `stat`.
Revert commit fe36527157ff96226f5309a99c806475ee0b75d2 and add a simple test for mz_os_get_file_date.
> Fix mz_os_get_file_date on POSIX

- mz_zip.c
Both calls to mz_zip_get_pk_verify already have the same #ifdef
> Fix "unused function" compiler warning if !HAVE_PKCRYPT

- mz_os.h
- mz_zip.c
All slashes should be written as forward slashes according
to the zip app note section 4.4.17.1.
Co-authored-by: jeremybernstein@users.noreply.github.com
> Fixed writing backslashes in zip on Windows.

- CMakeLists.txt
When running ctest it also builds and runs example and example64 from zlib.
The GCC CI builds were failing because example and example64 could not find
the header file zlib.h.
> Fixed GCC build compilation with ctest due to missing zlib.h

- CMakeLists.txt
- mz_os_posix.c
Simplifies the code. Upstream also recommends it.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
https://gitlab.freedesktop.org/libbsd/libbsd/-/issues/11#note_1417771
> build with libbsd-overlay

- mz_os_posix.c
We need to match the order of inclusions at the top of the file otherwise we might end up trying to use arc4random_buf() when available (because HAVE_ARC4RANODM_BUF is set) even though we hit HAVE_GETRANDOM first above and only included <sys/random.h> because of it.
Besides, if getrandom() is available, we should really prefer it anyway.
Fixes an implicit function declaration:
```
minizip-ng-3.0.6/mz_os_posix.c:124:5: error: implicit declaration of function 'arc4random_buf' [-Werror=implicit-function-declaration]
```
Signed-off-by: Sam James <sam@gentoo.org>
> Switch getrandom() and arc4random_buf() usage order

- mz_compat.c
- mz_zip.c
I found a few incompatibilities with the minizip from zlib while changing from an old zlib to zlib-ng + minizip-ng. These fixes are just suggestion as I don't really know anything about this code base, but working code is better than trying to explain what I mean.
I forgot to call unzCloseCurrentFile between calls to unzOpenCurrentFile. It didn't fail until it came across an uncompressed entry, then it tried to read approximately -800kiB through the IO-wrapper :). Forgetting to close the file is probably an user error but it looks like zlib handles that (on purpose) and will close any currently open entry in the open function. This commit replicates that behavior from zlib-minizip.
zlib code:
https://github.com/madler/zlib/blob/master/contrib/minizip/unzip.c#L1494
Calling …
> zlib-minizip compability fixes: CRC error on half-read files and unzOpenCurrentFile without close

- test/CMakeLists.txt
Distributions often do builds with no network access available for both security reasons and also to ensure reproducibility.
This change tells CMake to query the system for a copy of gtest, but if it's not available, it'll fall back to downloading via FetchContent.
> Search system for GTest before downloading. #654

- CMakeLists.txt
The current `liblzma` makes linke look for `libliblzma` as the `lib` prefix is added automatically. This is breaking static linking of library when using pkg-config for resolving dependencies.
> Fix private linking of LibLZMA

- mz_zip_rw.c
At least when using Info-ZIP 3.0, symlinks to both files and directories lack a trailing slash, so the second mz_path_remove_filename is unnecessary (and could break things if the parent directory doesn't precede the symlink in the file). If other implementations do add a trailing slash, the if statement should handle that.
> Create parent directory before extracting symlink

- mz_crypt_win32.c
- test/test_crypt.cc
Hei,
Here is the PR done on top of the `develop` branch instead of `master`.
For reference, my understanding of the issue is as follows:
- `CryptImportKey` fails with a play key of length 1 and returns `ERROR_INVALID_PARAMETER`, as previously raised here https://developercommunity.visualstudio.com/t/cryptimportkey-fails-to-import-plaintext-key-with/1215483. The link does not have the files mentioned, but I can reproduce that issue in a test program. 
- The original fix for that issue added a padding when the key length is odd.
- One issue with the original fix is that it assumed that key string is zero terminated and read past the provided length. That was already fixed in `c6c4f2cb2bcd28e220cee70cb3d4b0931e2f5ab4` and it's not yet in `master`.
- But padding when the key length is odd …
> Fixed incorrect handling of long odd length passwords

- CMakeLists.txt
Enable POSIX 2008 as it's needed for strdup(), otherwise we get:
```
/var/tmp/portage/sys-libs/minizip-ng-3.0.9/work/minizip-ng-3.0.9/mz_os.c: In function ‘mz_dir_make’:
/var/tmp/portage/sys-libs/minizip-ng-3.0.9/work/minizip-ng-3.0.9/mz_os.c:286:19: error: implicit declaration of function ‘strdup’ [-Werror=implicit-function-declaration]
286 |     current_dir = strdup(path);
|                   ^~~~~~
```
The man page for strdup says:
```
strdup():
_XOPEN_SOURCE >= 500
|| /* Since glibc 2.12: */ _POSIX_C_SOURCE >= 200809L
|| /* glibc <= 2.19: */ _BSD_SOURCE || _SVID_SOURCE
```
> CMake: set newer POSIX_C_SOURCE

- CMakeLists.txt
Non-UNIX platforms may support POSIX, partly or fully, through a compatibility layer of some kind. If a non-Windows platform does not have the UNIX CMake variable set, take the POSIX path through the CMake anyway.
Previously, for platforms without the WIN32 or UNIX variables set, the binaries would fail to link due to missing `mz_strm_os_*.c` and `mz_os_*.c` implementations. This change opens up POSIX support for platforms that fall through the crack without changing any logic for platforms that could previously be built for.
> Use POSIX implementation if platform is not Windows

- CMakeLists.txt
Using `cmake_dependent_option` overrides a previously set directory scope MZ_FETCH_LIBS variable. This means if a project sets MZ_FETCH_LIBS before adding minizip-ng as a subdirectory in order to force it to fetch zlib, it will set the variable to OFF, only use `find_library` and never fetch zlib on non-WIN32 systems. This is a regression from previous behaviour.
Instead, revert back to using `option` as this obeys a directory scope MZ_FETCH_LIBS variable set by a parent directory, allowing said parent directory to control zlib version.
> Fix MZ_FETCH_LIBS option for non-WIN32 systems

- mz_os_posix.c
Instead of always using CLOCK_MONOTONIC, use POSIX feature testing to determine support at compile-time, or if necessary at run-time using sysconf. If not supported, falls back to CLOCK_REALTIME.
> Add test for CLOCK_MONOTONIC support

- mz_crypt_apple.c
- mz_crypt_openssl.c
- test/test_crypt.cc
They leaded to overriding caller's local variables.
> Fix undefined behavior: strict aliasing rule violations

- mz_zip.c
This fixes a bug caused by https://github.com/zlib-ng/minizip-ng/issues/669
Above introduced the only instance where we actually check the return value of `mz_stream_set_prop_int64()`. Given any stream that is not a split stream, the call to `mz_stream_set_prop_int64(MZ_STREAM_PROP_DISK_NUMBER, ..)` will fail. So, do the same as in other places, ignore the return value of `mz_stream_set_prop_int64()`, but still check everything else.
> mz_zip.c - correctly close entry with streams other than split_stream

- CMakeLists.txt
CMake's `find_package()` will search [these paths](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure) when attempting to find a package config (note that while CMake's docs appear to indicate that `<name>` is optional (`*`) it's actually required):
```
<prefix>/
<prefix>/(cmake|CMake)/
<prefix>/<name>*/
<prefix>/<name>*/(cmake|CMake)/
<prefix>/<name>*/(cmake|CMake)/<name>*/
<prefix>/(lib/<arch>|lib*|share)/cmake/<name>*/
<prefix>/(lib/<arch>|lib*|share)/<name>*/
<prefix>/(lib/<arch>|lib*|share)/<name>*/(cmake|CMake)/
<prefix>/<name>*/(lib/<arch>|lib*|share)/cmake/<name>*/
<prefix>/<name>*/(lib/<arch>|lib*|share)/<name>*/
<prefix>/<name>*/(lib/<arch>|lib*|share)/<name>*/(cmake|CMake)/
```
The current minizip-ng config install location of …
> Fix cmake install location

- mz_zip.c
For example, opening an encrypted file with incorrect password should return MZ_PASSWORD_ERROR (as did 3.x).
The additional "err == MZ_OK" check makes sure that the correct error code is returned.
> Only return MZ_MEM_ERROR if no other error code was received before.

- CMakeLists.txt
Setting _POSIX_C_SOURCE on OpenBSD breaks the build. _BSD_SOURCE needs to be set at the same time to enable some functions.
```
In file included from /home/brad/tmp/ffmpeg-ports/ports/pobj/minizip-4.0.0/minizip-ng-4.0.0/test/test_main.cc:5:
In file included from /usr/local/include/gtest/gtest.h:55:
In file included from /usr/include/c++/v1/ostream:140:
In file included from /usr/include/c++/v1/locale:218:
/usr/include/c++/v1/__bsd_locale_fallbacks.h:122:17: error: use of undeclared identifier 'vasprintf'; did you mean 'vsprintf'?
int __res = vasprintf(__s, __format, __va);
^
/usr/include/c++/v1/cstdio:124:9: note: 'vsprintf' declared here
using ::vsprintf _LIBCPP_USING_IF_EXISTS;
^
In file included from /home/brad/tmp/ffmpeg-ports/ports/pobj/minizip-4.0.0/minizip-ng-4.0.0/test/test_main.cc …
```
> CMake: Fix build with OpenBSD #711

- CMakeLists.txt
zlib's minizip has SONAME 1. MZ_COMPAT intends to provide ABI and API compatibility, so its SONAME should match.
> CMake: fix SONAME for MZ_COMPAT

- mz_strm_zstd.c
Tell libzstd about the compression level passed to mz_strm_zstd.
Before this change, the default compression level (3) was always used.
> Fix zstd compression level

- minizip.c
- mz_strm_zstd.c
zstd supports regular compression levels 1 through 22.  This change enables minizip to accept command-line options of "-10" and above to set levels higher than 10.
This also changes minizip to send the special level of 0 when no command-line level option is specified, which indicates to use zstd's internal default level (currently 3, but potentially subject to change).
zstd also supports negative compression level values to enable "fast" compression.  These levels disable Huffman coding to achieve high bandwidth for streaming loads (comparable to LZ4).  I didn't attempt to support negative levels here as I'm not sure they're of much value in a non-streaming archive format.
> Support compression levels >= 10 and use zstd's internal default level.

- CMakeLists.txt
- minizip.pc.cmakein
If libz-ng is used the declared dependency on libz was wrong. Also it should be private if `Libs.private` is used. And if the libs are available as pkgconfig file we should use them instead of hardcoding liker flags.
> Fix pkgconfig file

- mz_compat.c
- mz_compat.h
Fixe Issue https://github.com/zlib-ng/minizip-ng/issues/706
Implicit conversion loses integer precision: 'unsigned long' to 'int32_t' (aka 'int') in line 124, 145 and 534
Implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') in line 599
> Fix Issue #706

- mz_strm_lzma.c
LZMA_PRESET_EXTREME is not a preset on its own but a flag which must be used together with a level. The difference between level 9 with and without the extreme flag also seems negligible, so this commit just passes through the level and maps -1 and invalid values to the default preset.
Closes #731
> Fix lzma compression level #731

- mz_os.c
https://github.com/zlib-ng/minizip-ng/issues/740
> Fix for filenames of the form "x/../y"

- mz_compat.c
This PR applies https://github.com/madler/zlib/pull/843 to minizip compat to close #736. It applies the [patch](https://github.com/madler/zlib/pull/843.patch) provided by @zmodem, but removed the checks for unused extra fields.
> This checks the lengths of the file name, and comment that would be put in the zip headers, and rejects them if they are too long. They are each limited to 65535 bytes in length by the zip format. This also avoids possible buffer overflows if the provided fields are too long.
> Reject overflows of zip header fields in minizip compat

- mz_compat.c
- mz_compat.h
- test/test_compat.cc
Replace the previous type with one that is compatible with an int in order to be identical to the interface used in madler's zlib.
Fixes #745.
> Fix unzLocateFile 3rd parameter

- mz_compat.c
- mz_compat.h
Building a project using the compat layer I noticed this warning..
```
In file included from /usr/local/include/minizip/unzip.h:11:
/usr/local/include/minizip/mz_compat.h:123:5: warning: 'MZ_COMPAT_VERSION' is not defined, evaluates to 0 [-Wundef]
^
```
> Silence MZ_COMPAT_VERSION warnings

- mz_strm_bzip.c
- mz_strm_zstd.c
```
/home/brad/tmp/minizip-ng/mz_strm_zstd.c:110:13: warning: variable 'total_in' set but not used [-Wunused-but-set-variable]
int32_t total_in = 0;
^
/home/brad/tmp/minizip-ng/mz_strm_bzip.c:117:13: warning: variable 'total_in' set but not used [-Wunused-but-set-variable]
int32_t total_in = 0;
^
```
> Silence -Wunused-but-set-variable warnings

- mz_strm_split.c
Decompress a zip multi-volume archive file without filename extension will cause an infinite loop.
payload: https://github.com/apache/commons-compress/blob/master/src/test/resources/COMPRESS-477/split_zip_created_by_zip/split_zip_created_by_zip.z01
change split_zip_created_by_zip.z01 filename to split_zip_created_by_zip, use minizip_cli to decompress this file(./minizip_cli -l /root/payloads/split_zip_created_by_zip) will cause an infinite loop.
Decompress multi-volume zip archive files in recover mode will cause an infinite loop.
payload: https://github.com/apache/commons-compress/blob/master/src/test/resources/COMPRESS-477/split_zip_created_by_zip/split_zip_created_by_zip.zip
split_zip_created_by_zip.zip, split_zip_created_by_zip.z01 and split_zip_created_by_zip.z02 are split zip files, …
> Infinite loop occurs while decompressing zip multi-volume archive file

- mz_compat.h
As the documented purpose of zlib-ng is to be a drop-in replacement of zlib, and minizip-ng a drop-in replacement of minizip, I wanted to clarify which parts of mz_compat.h are for the original minizip compatibility (permanent compatibility), and which parts are for older minizip-ng compatibility (deprecated usage).
I've consulted the current headers at https://github.com/madler/zlib/tree/develop/contrib/minizip and I've grouped them accordingly.
> Group compatibilities per origin

- mz_crypt_openssl.c
Since its very first release in 1998, OpenSSL has always returned an `unsigned long`:
https://github.com/openssl/openssl/blame/3edd7ed15de229230f74c79c3d71e7c9c674cf4f/crypto/err/err.c#L295
> Implicit conversion loses integer precision: 'unsigned long' to 'int32_t'

- mz_zip_rw.c
Xcode analyzer warning fix. When `MZ_ZIP_NO_CRYPTO` isn't defined, `err` is ignored and overwritten line 1347
> Value stored to 'err' is never read

- mz_strm_zlib.c
> The value is never actually read from 'zlib'

- mz_zip.c
When `dos_date` is `1`, `mz_zip_dosdate_to_raw_tm` should return a date in year 1979.
But the cast with `(uint16_t)` is incorrectly converting `-1` to `65535`, which turns the date to year 7441.
The issue may have originated from 35c6102e21d76019206154de07b8bb8577018825 or earlier (in unzip.c, `ptm->tm_mon =  (uInt)((((uDate)&0x1E0)/0x20)-1) ;`)
It was fixed in the legacy minizip about three years ago:
https://github.com/madler/zlib/commit/2014a993addbc8f1b9785d97f55fd189792c2f78
> fix incorrect dos date conversion

- compat/crypt.h
- compat/ioapi.h
- compat/unzip.h
- compat/zip.h
- mz_crypt.c
Fix #747
Supersedes #750 (cc @brad0)
I re-did the PR to account for the recent refactor in 7df56f7cc8438b1b67c881cad049b29bf075bccd
> Expose zlib constants for backwards compat

- doc/mz_zip_file.md
Hi, I found a typo in the documentation and fixed it. According to [appnote.txt#L910](https://github.com/yaslab/minizip/blob/develop/doc/zip/appnote.txt#L910) (and the [implementation](https://github.com/yaslab/minizip/blob/2c51fa7/mz_zip.h#L42)), `external_fa` is 4 bytes.
> FIx typo in `mz_zip_file.md`

- compat/unzip.h
Fix a compatibility regression from 7df56f7cc8438b1b67c881cad049b29bf075bccd
> missing mz_dos_date defines in unzip.h

- compat/ioapi.h
Fix #824.
Seems to have been a regression in 7df56f7cc8438b1b67c881cad049b29bf075bccd.
> align ZEXPORT definitions

- test/fuzz/unzip_fuzzer.c
- test/fuzz/zip_fuzzer.c
1. `zip_fuzzer` didn't work as expected - the stream was always closed
2. Added password support for `zip_fuzzer`
3. Added `mz_zip_set_recover` support to `unzip_fuzzer`
As a result line coverage is improved by ~13%
> Fix and improve fuzzers

- mz_zip.c
> fix: don't replace slashes on UNIX

- mz_os_win32.c
- test/CMakeLists.txt
- test/test_file.cc
_Should this target `develop` or `master`?_
This PR changes `mz_os_get_file_date` to use `GetFileAttributesExW` instead of `FindFirstFileW`, because `FindFirstFileW` fails on Windows Alternate Data Streams.
`mz_os_get_file_date` uses `FindFirstFileW`, which doesn't support Windows Alternate Data Streams (ADS).  The failed return value of `mz_os_get_file_date` is not checked by `mz_zip_writer_add_file`.  When an ADS is compressed with `mz_zip_writer_add_file`, the resulting entry has all-zero timestamps.  When we attempted to extract this file using various applications (Windows Explorer, 7-Zip, Python), the CRC check would fail.  In python, the failure was [here](https://github.com/python/cpython/blob/8f93dd8a8f237b277abad20d566df90c5cbd7f1e/Lib/zipfile/__init__.py#L948-L949).  When we …
> Fix Windows Timestamps for Alternate Data Streams

- minizip.c
- mz_crypt_openssl.c
- mz_strm_split.c
Fully similar issue as in zlib-ng: https://github.com/zlib-ng/zlib-ng/pull/1881
- mz_stream_split 120 -> 104 bytes
- mz_zip_file, mz_zip_entry 128 -> 120 bytes
- minizip_opt 32 -> 24 bytes
- mz_crypt_sha 32 -> 24 bytes
- mz_crypt_hmac 40 -> 32 bytes
> Align structures for 64-bit platforms

- minigzip.c
- minizip.c
- mz.h
- mz_zip.c
- mz_zip_rw.c
- test/test_compat.cc
- test/test_crypt.cc
- test/test_file.cc
- test/test_path.cc
- test/test_stream.cc
483950d09dad0c9f845c22112e2ffde81e0af951 introduced .clang-format which however is not respected in current v4.0.8 (55db144e03027b43263e5ebcb599bf0878ba58de). Hence, contributions via PR might get somehow noisy as this one shows.
> Apply Clang format

- compat/crypt.h
Fixes:
| In file included from /buildarea/tmp/work/core2-64-poky-linux/minizip-ng/4.0.8/git/test/test_compat.cc:17:
| /buildarea/tmp/work/core2-64-poky-linux/minizip-ng/4.0.8/git/compat/crypt.h:62:9: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
|    62 |         register int keyshift = (int)((*(pkeys + 1)) >> 24);
|       |         ^~~~~~~~
| 1 error generated.
> crypt.h: Remove register keyword

- mz_zip_rw.c
Before Clang 19 -O2:
After Clang 19 -O2:
> Pre-calc length destination directory before while loop

- .gitignore
When I run those commands, I get a lot of folders created:
```
cmake -S . -B . -D MZ_BUILD_TESTS=ON -D MZ_BUILD_UNIT_TESTS=ON -D BUILD_SHARED_LIBS=OFF -D CMAKE_BUILD_TYPE=Debug
cmake --build . --config Debug
ctest --output-on-failure -C Debug
```
So I'm adding those folders to .gitignore.
> gitgnore build folders

- .github/workflows/build.yml
The minimum supported ubuntu is now 22.04: https://github.com/actions/runner-images
The minimum supported clang is now 13: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
[edit]
I was able to downgrade to clang 11, but not clang 10.
> updating github actions for ubuntu-22.04

- mz_zip.c
Testing, on UNIX system:
```
touch a\\
./minizip file.zip a\\
rm a\\
./minizip -x file.zip
ls a\\
```
> fix: unzipping with backslash at the end of the filename

- mz_os_posix.c
The existing list of supported encodings was added by ea5e45dfe2c42ade58e260cb14b910f75b385525.
That list was quite limited.
In a more practical way, this PR supports any encoding that iconv supports:
```
➜  iconv --list | grep " [0-9]\+ "
CP037 037 EBCDIC-CP-CA EBCDIC-CP-NL EBCDIC-CP-US EBCDIC-CP-WT IBM037
CP038 038 EBCDIC-INT IBM038
CP10000 10000 CP10000_MACROMAN
CP10006 10006 CP10006_MACGREEK
CP10007 10007 CP10007_MACCYRILLIC MS-MAC-CYRILLIC
CP10029 10029 CP10029_MACLATIN2
CP1006 1006 MSCP1006
CP10079 10079 CP10079_MACICELANDIC
CP10081 10081 CP10081_MACTURKISH
CP1026 1026 IBM1026
CP1046 1046 IBM1046
CP1124 1124 IBM1124
CP1125 1125 IBM1125
CP1129 1129 IBM1129
CP1131 1131 IBM1131
CP1133 1133 IBM-CP1133 IBM1133
CP1161 1161 CSIBM1161 IBM-1161 IBM1161
CP1162 1162 CSIBM1162 IBM-1162 IBM1162 …
```
> Support any character encoding
