zlib-ng/minizip-ng

miniunz.c
unzip.c
zip.c

Fix incorrect range comparisons

---

unzip.c
zip.c

Yeah, so, ummm...
Oops.  Totally misread this code.  Sorry about that.

Revert range comparison "fix"

---

unzip.c

It seems there's quite a few local variables and struct fields, which overflow when file sizes go above 4GB (32bit boundary). Most of the overflows seem to be benign, but one in particular causes the pfile_in_zip_read_info->total_out_64 to go back to 0, which results in reading past the file compressed buffer.
Surprisingly this issue only surfaces in 64-bit builds. My theory (which I didn't fully verify) is that the stream and bstream fields overflow in sync in 32-bit environment. I've patched it and it seems to be working fine in my setup (iOS project, verified with huge archives on i386/x86_64 sim and armv7/arm64 devices, llvm compiler), but I don't have the resources to verify/patch the problem for other platforms/compilers.

Fixed an arithmetic overflow leading to unzipping failure in 64bit mode

---

unzip.c

missing ; in unzip.c

---

CMakeLists.txt

Hey there,
I just created a pretty simple CMake project file for the minzip environment so cross-platform build will get more easy. I'd like to contribute this file - just take a look and give me feedback if you want to have it or if anything is missing.
-Matthias

added CMakeConfiguration for minizip project

---

unzip.c

Build fails when NOUNCRYPT is set.

Fix Build Error

---

CMakeLists.txt

added missing link library for minzip target

---

ioapi.c
ioapi.h
ioapi_buf.c
minizip.c
zip.c

The PR is inspired by [this issue](https://github.com/gianlucabertani/Objective-Zip/issues/37).

Some issues fixed for Apple LLVM Compiler (Xcode default compiler)

---

unzip.c

This refactoring allows to deal with three almost identical blocks of code to reduce cyclomatic complexity. It also deals with the warning of `lSeek` being unread (see #84).

factoring unz64local_ReadField

---

Minizip.podspec
aes/aesopt.h
ioapi.c

minimum changes for latest to build on iOS

compatibility with __APPLE__

---

crypt.c

cf. https://msdn.microsoft.com/en-us/library/windows/desktop/aa382471(v=vs.85).aspx
Change-Id: I9898deac5c4b48abac49bae01db218d06206430b

add missing #include

---

unzip.c

fix Memory Error with AES

---

ioapi.h

android support

---

Minizip.podspec
README.md

https://en.wikipedia.org/wiki/MacOS

naming for macOS and Xcode

---

unzip.c

Allow unzipping the sample from #178 without error.

compatibility with empty zip files

---

unzip.c

workaround incorrect headers (fix #159)

---

CMakeLists.txt
mz_zip.c

(See issue nmoinvaz/minizip#264)

Partial fix for building without zlib

---

mz_compat.h

Ref: https://github.com/madler/zlib/blob/v1.2.11/contrib/minizip/zip.h#L112-L114

make APPEND_STATUS_* values identical to minizip1 (for compatibility)

---

CMakeLists.txt

Very simple commit adding API versioning to the build process.

Adds API versioning.

---

README.md

* also fold some long lines
* remove double EOL at EOF

README: Update/add Travis CI links, use HTTPS

---

mz_crypt_openssl.c

fixed for openssl 1.1.0 to 1.1.1 
not test on openssl 1.0.2x
for #329

fixed for openssl 1.1.0 to 1.1.1

---

CMakeLists.txt

@nmoinvaz sorry, but I screwed up the last fix - it actually did not fix the underlying issue
I removed the complete `if...end` statement since this is not necessary, CMake will take care of the generation. 
To make it up to you, I also removed the unnecessary trailing spaces :)
Please consider upgrading your travis CI to also do the installation step in order to figure these kinds of problems out in the first place.

Fix package config install target

---

mz_os_win32.c

Please see issue here: https://github.com/nmoinvaz/minizip/issues/369

Allow recursively creating Windows path to fix #369

---

Minizip.podspec

- added a missing mz_strm_os header

Missing mz_strm_os.h in the podspec

---

mz_strm_os_posix.c

Use lseek64 on Android

---

mz_strm_zstd.c
mz_zip.c

@nmoinvaz 
I tried it tonight(UTC+8), and there seems to be an error in your zstd decompression code. This is an improvement, but I did not add enough tests, I hope you can review it. Thanks.

fix decompress zstd error

---

CMakeLists.txt

CMake: fix error message for zstd fetching

---

CMakeLists.txt

adds suffix in config files to seperate installs from original minizip, and also helps in creating port file in vcpkg,

reflects-suffix-in-config-file

---

mz.h
mz_crypt_apple.c
mz_crypt_openssl.c
mz_crypt_win32.c
test/test.c

If you wish function pointers (virtual functions) may be used instead of the switch statements.

Add SHA224, SHA384, SHA512 to crypt.

---

mz_zip_rw.c

Convenient for heck like [`Taromati2/nar-thumbnail-provider@6b20d28/NarThumbnailProvider/zip_reader_open_IStream.cpp`](https://github.com/Taromati2/nar-thumbnail-provider/blob/6b20d2896822754c9ac5e4c69999d0762b4f23df/NarThumbnailProvider/zip_reader_open_IStream.cpp)

memstream delete -> stream delete

---

mz_os_win32.c

Fix find handle leak in low memory situations

---

README.md

Mention support for ZIP64 on features list. 

---

mz_zip.c

mz_zip.c: perform bitshift when converting POSIX to win32 attributes

---

mz_os.c

fixes https://github.com/zlib-ng/minizip-ng/issues/737

#737: Get mz_dir_make to test for an empty path

---

mz_os.c

Fix for https://github.com/zlib-ng/minizip-ng/issues/739

Check for zero length path in mz_path_has_slash

---

mz_compat.c
mz_os_win32.c
mz_zip.c

Adjust the annotation style mentioned by #754

Update mz_zip.c comments style 

---

compat/ioapi.c
mz_strm.c
mz_strm_buf.c
mz_strm_bzip.c
mz_strm_lzma.c
mz_strm_os_posix.c
mz_strm_pkcrypt.c
mz_strm_split.c
mz_strm_zlib.c
mz_strm_zstd.c
mz_zip.c

References:
- https://stackoverflow.com/a/18775633
- https://pubs.opengroup.org/onlinepubs/009695399/functions/free.html

Remove excess checks before free()

---

minizip.c
mz_zip_rw.c

Consider passed codepage on listing and extraction callback

---

mz_zip_rw.c

Support star in filename

---

mz_zip.c

Fix #836
Note to @nmoinvaz this is the last Pull Request that I plan to make for a while, as I finished fixing all minizip and ZipArchive known bugs.
So feel free to publish a release after that.

fix copy encrypted file info
